# Generated by Django 5.2.6 on 2025-09-09 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Tenant ID for multi-tenant isolation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Viewer', 'Viewer')], default='Viewer', max_length=20),
        ),
    ]
