# Generated by Django 5.2.6 on 2025-09-24 11:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('rider_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck')], max_length=20)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'riders',
                'indexes': [models.Index(fields=['tenant_id'], name='riders_tenant__ef6d4c_idx'), models.Index(fields=['tenant_id', 'status'], name='riders_tenant__3a5f22_idx'), models.Index(fields=['tenant_id', 'vehicle_type'], name='riders_tenant__5c510c_idx')],
                'unique_together': {('tenant_id', 'email')},
            },
        ),
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('dispatch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('order_id', models.UUIDField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=50)),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('pickup_location', models.JSONField(blank=True, default=dict)),
                ('delivery_location', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('actual_duration', models.PositiveIntegerField(blank=True, help_text='Actual duration in minutes', null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_orders', to='riders.rider')),
            ],
            options={
                'db_table': 'dispatch_orders',
                'indexes': [models.Index(fields=['tenant_id'], name='dispatch_or_tenant__01e5b0_idx'), models.Index(fields=['tenant_id', 'status'], name='dispatch_or_tenant__cfa187_idx'), models.Index(fields=['tenant_id', 'rider', 'status'], name='dispatch_or_tenant__72258c_idx'), models.Index(fields=['tenant_id', 'priority'], name='dispatch_or_tenant__079ded_idx'), models.Index(fields=['order_id'], name='dispatch_or_order_i_4067dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiderLocationHistory',
            fields=[
                ('location_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='riders.rider')),
            ],
            options={
                'db_table': 'rider_location_history',
                'indexes': [models.Index(fields=['rider', 'timestamp'], name='rider_locat_rider_i_92b1d6_idx')],
            },
        ),
    ]
