# Generated by Django 5.2.6 on 2025-11-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_paystacktransaction_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
