# Generated by Django 5.2.6 on 2025-10-10 13:51

import django.db.models.deletion
import main_services.analytics.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDailySales',
            fields=[
                ('sales_rollup_id', models.UUIDField(default=main_services.analytics.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('top_skus', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_daily_sales',
                'indexes': [models.Index(fields=['tenant_id', 'date'], name='analytics_d_tenant__18d80f_idx'), models.Index(fields=['tenant_id', 'total_revenue'], name='analytics_d_tenant__9c4d96_idx')],
                'unique_together': {('tenant_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsDailyTopSKU',
            fields=[
                ('topsku_id', models.UUIDField(default=main_services.analytics.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('sku_id', models.UUIDField(db_index=True)),
                ('sku_name', models.CharField(max_length=255)),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_daily_topsku',
                'indexes': [models.Index(fields=['tenant_id', 'date'], name='analytics_d_tenant__e06682_idx'), models.Index(fields=['tenant_id', 'sku_id'], name='analytics_d_tenant__e0f6ee_idx'), models.Index(fields=['tenant_id', 'date', 'sold_quantity'], name='analytics_d_tenant__469b45_idx')],
                'unique_together': {('tenant_id', 'date', 'sku_id')},
            },
        ),
        migrations.CreateModel(
            name='StockoutIncident',
            fields=[
                ('stockout_id', models.UUIDField(default=main_services.analytics.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('sku_id', models.UUIDField(db_index=True)),
                ('sku_name', models.CharField(max_length=255)),
                ('incident_date', models.DateField(db_index=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_stockout_incident',
                'indexes': [models.Index(fields=['tenant_id', 'incident_date'], name='analytics_s_tenant__5cfca8_idx'), models.Index(fields=['tenant_id', 'sku_id'], name='analytics_s_tenant__8a025b_idx')],
            },
        ),
    ]
