# Generated by Django 5.2.6 on 2025-10-11 16:09

import main_services.analytics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDailyStock',
            fields=[
                ('stock_rollup_id', models.UUIDField(default=main_services.analytics.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('total_stock', models.IntegerField(default=0)),
                ('low_stock_count', models.PositiveIntegerField(default=0)),
                ('stockout_count', models.PositiveBigIntegerField(default=0)),
                ('adjustments_summary', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_daily_stock',
                'indexes': [models.Index(fields=['tenant_id', 'date'], name='analytics_d_tenant__23f16d_idx')],
                'unique_together': {('tenant_id', 'date')},
            },
        ),
    ]
