# Generated by Django 5.2.6 on 2025-10-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analyticsdailystock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analyticsdailytopsku',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='analyticsdailytopsku',
            name='sku_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='analyticsdailytopsku',
            name='sku_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsdailytopsku',
            name='sku_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
