# Generated by Django 5.2.6 on 2025-09-11 15:14

import django.db.models.deletion
import main_services.inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('sku_id', models.UUIDField(default=main_services.inventory.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('sku_code', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('category', models.CharField(db_index=True, max_length=128)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_level', models.IntegerField(default=0)),
                ('supplier_id', models.UUIDField(blank=True, null=True)),
                ('track_batches', models.BooleanField(default=False)),
                ('reorder_threshold', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'category'], name='inventory_s_tenant__b260c8_idx'), models.Index(fields=['tenant_id', 'stock_level'], name='inventory_s_tenant__f11e43_idx')],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.UUIDField(default=main_services.inventory.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('batch_number', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('remaining_quantity', models.IntegerField()),
                ('received_at', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.sku')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.UUIDField(default=main_services.inventory.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('sku_name', models.CharField(max_length=255)),
                ('current_stock', models.IntegerField()),
                ('threshold', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('low_stock', 'Low stock'), ('batch_expiry', 'Batch expiry')], db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sku')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('adjustment_id', models.UUIDField(default=main_services.inventory.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('correction', 'Correction'), ('transfer', 'Transfer')], max_length=32)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.sku')),
            ],
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['tenant_id', 'expiry_date'], name='inventory_b_tenant__c4c360_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['tenant_id', 'sku', 'batch_number'], name='inventory_b_tenant__d7daf2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['tenant_id', 'sku', 'created_at'], name='inventory_s_tenant__ceeae6_idx'),
        ),
    ]
