# Generated by Django 5.2.6 on 2025-09-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_batch_remaining_quantity'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='batch',
            name='inventory_b_tenant__c4c360_idx',
        ),
        migrations.RemoveIndex(
            model_name='batch',
            name='inventory_b_tenant__d7daf2_idx',
        ),
    ]
