# Generated by Django 5.2.6 on 2025-11-21 10:17

import main_services.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_batch_inventory_b_tenant__c4c360_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(blank=True, db_index=True, default=main_services.inventory.models.generate_uuid, editable=False, max_length=64, null=True),
        ),
    ]
