# Generated by Django 5.2.6 on 2025-11-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_sku_sku_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='price',
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(blank=True, db_index=True, default='2JH3DX', editable=False, max_length=64, null=True),
        ),
    ]
