# Generated by Django 5.2.6 on 2025-11-21 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0007_sku_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='product',
            field=models.OneToOneField(blank=True, db_column='product_sku_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sku', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(blank=True, db_index=True, default='EAA158', editable=False, max_length=64, null=True),
        ),
    ]
