# Generated by Django 5.2.6 on 2025-11-21 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0008_alter_sku_product_alter_sku_sku_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sku', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(blank=True, db_index=True, default='QKENP5', editable=False, max_length=64, null=True),
        ),
    ]
