# Generated by Django 5.2.6 on 2025-11-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_sku_product_alter_sku_sku_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='product',
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(blank=True, db_index=True, default='PT92BK', editable=False, max_length=64, null=True),
        ),
    ]
