# Generated by Django 5.2.6 on 2025-11-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_sku_product_alter_sku_sku_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(blank=True, db_index=True, default='X9I51F', editable=False, max_length=64, null=True),
        ),
    ]
