# Generated by Django 5.2.6 on 2025-11-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_sku_sku_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(blank=True, db_index=True, default='19IJ0I', editable=False, max_length=64, null=True),
        ),
    ]
